version: "3.8"
networks:
  lan:
services:
  registrator:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: registrator
      network: host
    container_name: reg
    networks:
      - lan
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://reg:9090/health" ]
      interval: 2s
      timeout: 2s
      retries: 10
  load_balancer:
    build: ./load_balancer
    ports:
      - "6868:8888"
  node:
    build: ./node
    ports:
      - "9050-9070:5050"
    depends_on:
      registrator:
        condition: service_healthy
    networks:
      - lan
  api:
    restart: unless-stopped
    networks:
      - lan
    depends_on:
      registrator:
        condition: service_healthy
    build: ./api
    ports:
    - "7878:8888"